<img src="https://miro.medium.com/max/1400/1*qePzd2m_uIPvsozXYh89CQ.png">

    
NumPy, Python programlama diline ait çok boyutlu dizilerle ve matrislerle çalışmamıza yardım eden ileri düzey matematiksel işlemler yapabileceğimiz bir kütüphanedir. Günümüzde özellikle veri bilimi üzerine çalışanlar başta olmak üzere Numpy, Python programlayanlar tarafından çok sık kullanılan bir kütüphanedir.
    
Dizinler üzerinde matematiksel, cebirsel ve istatistiksel operasyonlar uygulamak için kullanılır.

Numpy'in diğer kütüphanelere göre üstünlüklerinden birisi de çok boyutlu dizilerle işlem yapabilmemizi sağlayan fonksiyonlara sahip olmasıdır. 

Çok boyutlu dizileri hatırlayalım:
<img src="https://i.stack.imgur.com/NWTQH.png">

    
<p>
    

    


<H2></H2>
<H2>Numpy ve Listelerin Farkları</H2>

<H3>List kullanımı:  </H3>

a = [1,5,10]   
b = [1,2,3]

a * b => HATA !
                       
<p><p><p><p>
    
    
<H3>NumPy kullanımı:    </H3>

a = numpy.array([1,5,10]) 
    
b = numpy.array([1,2,3])

a * b = numpy.array([1,10,30])

In [1]:
import numpy as np

In [2]:
a = np.array([1,5,10])
print(a)

[ 1  5 10]


In [3]:
b = np.array([[1,7,20], [5, 8, 9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]



Dizinin boyutunu öğrenmek için ndim kullanırız:

In [4]:
b.ndim

2

In [5]:
a.ndim

1

In [10]:
# 2 satır 3 sütunlu dizimizin boyunu öğrenmek için shape kullanılır:

b.shape


(2, 3)

In [11]:
a.dtype

dtype('int32')

In [12]:
x = np.array([1.0,5.4,10.42])
x.dtype

dtype('float64')

Dizinin belirli bir hücresine erişmek için satır ve sütun numaralarını kullanırız:

In [13]:
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [14]:
b[0,2]

20

In [15]:
b[1,1]

8

In [16]:
b[0]

array([ 1,  7, 20])

In [ ]:
ilk satırdaki ikinci ve ücüncü elemanlara - yani 7 ve 20'ye erişmek için : kullanırız:

In [17]:
b[0, 1:]

array([ 7, 20])

In [18]:
b[1, 1] = 18
b[1, 1]

18

In [19]:
b

array([[ 1,  7, 20],
       [ 5, 18,  9]])

<H3> Otomatik dizi oluşturma </H3>

In [20]:
# Tümü sıfır matris/dizi
dizi_s = np.zeros((2,3))
dizi_s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# Tümü aynı değer olan dizi
dizi1= np.full((4,4), 50)
dizi1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [22]:
# Random dizi oluşturma
dizi2 = np.random.rand(4,3)
dizi2

array([[0.14925805, 0.47734539, 0.23758445],
       [0.18349251, 0.35557823, 0.01181234],
       [0.44316011, 0.06947011, 0.46490424],
       [0.24576153, 0.118214  , 0.9016374 ]])

In [24]:
# otomatik random int dizi oluşturma
dizi3 = np.random.randint(0,100,size=(5,5))
dizi3

array([[52, 40, 93, 92, 15],
       [51, 33, 73,  0, 62],
       [30,  4, 16, 42, 39],
       [37,  2, 44,  6, 21],
       [94, 76, 40, 93, 42]])

<H3> Dizi kopyalarken dikkat !!! </H3>

In [25]:

a = np.array([1,2,3])
b = a
b[0] = 90

print(a)

[90  2  3]


In [26]:
# b bir pointer gibi a'nın gösterdiği aynı memory lokoasyonunu gösteriyor o nedenle b!deki değişiklik a da da oluyor.
# bu tarz durumlarla karşılaşmamak için copy() fonksyionunu kullanın:
a = np.array([1,2,3])
b = a.copy()
b[0] = 90

print(a)

[1 2 3]


In [27]:
print(b)

[90  2  3]


<H3> Dizilerde Matematiksel İşlemler </H3>

In [28]:

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [29]:

a + 4

array([5, 6, 7, 8])

In [30]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

In [31]:

b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [32]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)


<H3> İstatistik </H3>

In [33]:
dizi4 = np.array([[1,2,3],[4,5,6]])
dizi4

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.min(dizi4)

1

In [36]:
np.max(dizi4)

6

In [37]:

np.sum(dizi4)

21

<H3> Dosyadan dizi yükleme </H3>

In [38]:
filedata = np.genfromtxt('ornek.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[1 2 3 4 5 6 7]
 [8 9 7 8 9 9 8]
 [3 3 3 5 7 9 0]]


In [39]:
filedata[1,0]

8